- .github/dependabot.yaml
- .github/workflows/ci.yml
> Add CI Workflow

- deployment/grafana/deployment.yml
- deployment/grafana/kustomization.yml
- deployment/loki/kustomization.yml
- deployment/prometheus/deployment.yml
- deployment/prometheus/kustomization.yml
- deployment/promtail/kustomization.yml
There are no breaking changes, there are just improvements on UI and minor fixes for. Also, syntax fix in kustomizer
> version bump for Grafana and Prometheus

- deployment/loki/statefulset.yml
- deployment/promtail/daemonset.yml
As these application are closely coupled it is better to have the same version
> Promtail and Loki version

- deployment/grafana/deployment.yml
Also, removed net_bind as that is no longer required
> Removed environment variables for Grafana Kubernetes deployment - this will be vanila deployment

- deployment/grafana/deployment.yml
- deployment/loki/statefulset.yml
- deployment/prometheus/deployment.yml
- deployment/tempo/statefulset.yml
> services metrics scrape

- deployment/tempo/account.yml
> Tempo: disbale service account mount

- deployment/loki/statefulset.yml
- deployment/promtail/daemonset.yml
- deployment/tempo/statefulset.yml
This is for bugfixes and minor security improvements
> minor version bumps for grafana loki, promtail and tempo

- deployment/grafana/deployment.yml
This version contains bug fixes and minor improvements - for full details https://github.com/grafana/grafana/releases/tag/v10.1.0
> version bump for Grafana to 10.1.0

- deployment/grafana/deployment.yml
- minor version bump for grafana
> minor version bump for grafana

- deployment/loki/statefulset.yml
- deployment/prometheus/deployment.yml
- deployment/promtail/daemonset.yml
- deployment/tempo/statefulset.yml
This will be tested in integration env
> version bump for Tempo, Loki, Promtail and Prometheus

- deployment/kustomization.yml
> removed common annotations in main deployment due to gke errors

- deployment/grafana/deployment.yml
- deployment/loki/statefulset.yml
- deployment/prometheus/deployment.yml
- deployment/promtail/daemonset.yml
- deployment/tempo/statefulset.yml
> minor version bumps for Grafana, Loki, Promtail, Promethues and Tempo

- deployment/promtail/daemonset.yml
- deployment/promtail/promtail-cm.yml
> promtail: removed args config file

- deployment/prometheus/deployment.yml
- chore(prometheus): version bump
> chore(prometheus): version bump

- .github/dependabot.yaml
- chore: added dependabot docker
> chore: added dependabot docker

- deployment/grafana/deployment.yml
- deployment/grafana/kustomization.yml
- deployment/loki/kustomization.yml
- deployment/loki/statefulset.yml
- deployment/prometheus/deployment.yml
- deployment/prometheus/kustomization.yml
- deployment/promtail/daemonset.yml
- deployment/promtail/kustomization.yml
- deployment/tempo/kustomization.yml
- deployment/tempo/tempo-cm.yml
- chore: tempo config update and services version bump
> chore: tempo config update and services version bump

- .github/workflows/stale.yml
- feat: add issue stale workflow
> feat: add issue stale workflow

- deployment/grafana/cm.yml
- deployment/grafana/deployment.yml
- deployment/grafana/service.yml
- deployment/kustomization.yml
- deployment/mimir/statefulset.yml
- deployment/prometheus/deployment.yml
- deployment/prometheus/service.yml
- feat: modularized datasources to individual files
> feat: modularized datasources to individual files

- deployment/kustomization.yml
- deployment/namespace.yml
Hi there! I found your repo and wanted to try it because I had trouble with Prometheus, Loki, & Promtail a few weeks ago. Your project could have really helped me speed up my work back then.
When I tried your setup, I saw right away that a namespace was missing. So, I added it to the kustomization config.
This is my first time trying to contribute to open source with this Pull Request. I hope you like it, and I'm excited about maybe working together more in the future. :)
> Add monitoring namespace creation to Kustomization config

- deployment/prometheus/deployment.yml
- chore: add alert rules mount path
> chore: add alert rules mount path

- deployment/tempo/cm.yml
> chore: updated tempo config file

- deployment/loki/statefulset.yml
- deployment/mimir/statefulset.yml
- deployment/promtail/daemonset.yml
> chore: version bumps for Grafana, Loki, Promtail and Mimir

- deployment/mimir/statefulset.yml
- deployment/tempo/statefulset.yml
> chore: disable auto mount service account token for mimir and tempo

- deployment/loki/cm.yml
- deployment/loki/statefulset.yml
- deployment/promtail/daemonset.yml
> chore: version bump for Loki and Promtail

- deployment/tempo/cm.yml
Included autocomplete_filtering_enabled and set autocomplete_filtering_enabled to true
> chore: update config map for tempo

- deployment/grafana/cm.yml
- **fix: update pyroscope data source**
- **chore: update pyroscope datasource**
> chore: update pyroscope datasource

- deployment/loki/statefulset.yml
- deployment/prometheus/deployment.yml
- deployment/promtail/daemonset.yml
- feat: minor upgrade promethues, promtail and loki
> feat: minor upgrade promethues, promtail and loki

- deployment/prometheus/cm.yml
Signed-off-by: Said Sef <saidsef@gmail.com>
> feat: add promql for nginx controller

- deployment/prometheus/cm.yml
> fix: promql variable error

- deployment/prometheus/cm.yml
> fix: promql variable error quotes

- deployment/prometheus/cm.yml
- deployment/prometheus/deployment.yml
Also, reduce promethues logging to warn
> fix: add jvm metrics alert

- deployment/grafana/deployment.yml
- deployment/loki/statefulset.yml
- deployment/mimir/cm.yml
- deployment/mimir/statefulset.yml
- deployment/prometheus/deployment.yml
- deployment/promtail/daemonset.yml
- deployment/tempo/statefulset.yml
This is due to monitoring services showing that the services are over provisioned
> feat: adjust services resources cpu and memory

- deployment/mimir/cm.yml
> fix: mimir filesystem storage dir

- deployment/grafana/deployment.yml
- deployment/loki/statefulset.yml
- deployment/prometheus/deployment.yml
- deployment/promtail/daemonset.yml
- deployment/tempo/statefulset.yml
- feat: version bump lgtm stack components
> feat: version bump lgtm stack components

- deployment/grafana/deployment.yml
- feat: enabled pyrosocpe datasource
> feat: enabled pyrosocpe datasource

- deployment/grafana/deployment.yml
https://github.com/advisories/GHSA-h493-wm58-vgvj
> fix: Migration Assistant issue

- deployment/grafana/deployment.yml
- deployment/loki/statefulset.yml
- deployment/promtail/daemonset.yml
- feat: minor version bumps for grafana, loki and promtail
> feat: minor version bumps for grafana, loki and promtail

- deployment/mimir/statefulset.yml
- deployment/pyroscope/deployment.yml
- deployment/tempo/statefulset.yml
- feat: minor version bumps for tempo, mimir and pyrosocpe
> feat: minor version bumps for tempo, mimir and pyrosocpe

- deployment/tempo/cm.yml
- fix: add metrics generator processors
> fix: add metrics generator processors

- deployment/grafana/cm.yml
- deployment/tempo/cm.yml
- fix: add overrides defaults to tempo config map
> fix: add overrides defaults to tempo config map

- deployment/loki/statefulset.yml
- deployment/promtail/daemonset.yml
- feat: minor version bump for grafana loki and promtail
> feat: minor version bump for grafana loki and promtail

- deployment/grafana/deployment.yml
- chore: grafana version bump v11.6.0
> chore: grafana version bump v11.6.0

- deployment/loki/statefulset.yml
- deployment/promtail/daemonset.yml
- chore: loke minor version update v3.4.3
> chore: loke minor version update v3.4.3

- README.md
- deployment/alloy/cm.yml
- deployment/alloy/cr.yml
- deployment/alloy/crb.yml
- deployment/alloy/daemonset.yml
- deployment/alloy/kustomization.yml
- deployment/alloy/sa.yml
- deployment/alloy/service.yml
- deployment/kustomization.yml
- feat: add grafana alloy to grafana stack
> feat: add grafana alloy to grafana stack

- deployment/alloy/kustomization.yml
- deployment/grafana/kustomization.yml
- deployment/loki/kustomization.yml
- deployment/mimir/kustomization.yml
- deployment/prometheus/kustomization.yml
- deployment/promtail/kustomization.yml
- deployment/pyroscope/deployment.yml
- deployment/pyroscope/kustomization.yml
- deployment/pyroscope/service.yml
- deployment/tempo/kustomization.yml
- chore: clean up services name selectors
> chore: clean up services name selectors

- README.md
- chore: add wrapper to architecture diagram
> chore: add wrapper to architecture diagram

- deployment/tempo/statefulset.yml
- chore: increase tempo memory resource
> chore: increase tempo memory resource

- README.md
- deployment/grafana/deployment.yml
- deployment/prometheus/deployment.yml
- chore: minor version bumps for grafana and prometheus
Resolves #173
> chore: minor version bumps for grafana and prometheus

- README.md
- deployment/alloy/cm.yml
- deployment/alloy/daemonset.yml
- deployment/alloy/service.yml
- deployment/beyla/cm.yml
- deployment/beyla/cr.yml
- deployment/beyla/crb.yml
- deployment/beyla/daemonset.yml
- deployment/beyla/kustomization.yml
- deployment/beyla/sa.yml
- deployment/kustomization.yml
- deployment/prometheus/deployment.yml
- deployment/tempo/cm.yml
Implements the changes described in Issue #178
This PR introduces Grafana Beyla eBPF application auto-instrumentation to the monitoring stack.
- Adds Grafana Beyla eBPF auto-instrumentation for automatic application monitoring
- Configures OpenTelemetry integration with Alloy collector
- Updates documentation and architecture diagrams
- Provides zero-code instrumentation for HTTP/gRPC services
- Captures RED metrics (Rate, Errors, Duration) automatically
- Enhances observability without application modifications
- **ConfigMap**: OpenTelemetry endpoints, service discovery, attribute filtering
- **DaemonSet**: Privileged deployment with necessary eBPF capabilities
- **RBAC**: ClusterRole and ServiceAccount for Kubernetes API access
- **Kustomization**: Deployment orchestration
- Added OTel …
> feat: add grafana beyla ebpf application auto-instrumentation

- README.md
- chore: update services descriptions
> chore: update services descriptions

- deployment/alloy/cm.yml
- deployment/alloy/daemonset.yml
- deployment/beyla/cm.yml
- deployment/beyla/daemonset.yml
- deployment/tempo/cm.yml
- deployment/tempo/statefulset.yml
- Added GOMEMLIMIT environment variables for Alloy, Beyla and Tempo components
- Increased memory allocations for Alloy and Tempo
- Optimized Beyla configuration to exclude more system components
- Adjusted Tempo compaction settings and max attribute bytes
- Added log level and format configuration for Tempo
- Implemented log age filtering in Alloy
- To improve stability and prevent OOM kills
- To optimize memory usage across the stack
- To reduce noise in metrics collection
- To improve trace retention and compaction efficiency
- To standardize logging format
- More stable operation with defined memory limits
- Better resource utilization
- Cleaner metrics collection
- More efficient trace storage
> feat: optimize resource allocation and performance tuning for Loki stack

- README.md
- deployment/grafana/cm.yml
- deployment/grafana/deployment.yml
- 🏗️ Added comprehensive Grafana INI configuration
- 📊 Configured default dashboard settings
- 🛠️ Fixed plugin installation with tmp directory mount
- 📝 Updated documentation to reflect Grafana Stack changes
Pre-installed 17+ cutting-edge plugins including:
- `aws-datasource-provisioner-app`
- `grafana-llm-app` 
- `grafana-synthetic-monitoring-app`
- `redis-explorer-app`
- `grafana-oncall-app`
- `grafana-investigations-app`
- And many more!
- Enabled plugin admin features
- Configured proper logging format
- Set up feature toggles for enhanced functionality
- Improved datasource configuration
These changes provide a robust, production-ready Grafana setup with:
- Better observability
- Enhanced plugin management
- Improved performance
- More flexible configuration options
Resolves: #193
> ✨ feat: Supercharge Grafana with 17+ plugins & enhanced configuration 🚀

- deployment/loki/cm.yml
- deployment/loki/statefulset.yml
- Enabled and configured Loki pattern ingester for advanced log pattern detection
- Migrated schema configuration from v11/boltdb to v13/tsdb with 24h index period
- Upgraded Loki container image from v3.5.3 to v3.5.5
- Enhanced probe configurations with TCP socket liveness check and extended timeouts
- Restructured configuration layout for improved clarity and maintainability
- TSDB provides superior performance, scalability, and feature completeness compared to deprecated boltdb-shipper
- Pattern ingester enables sophisticated log pattern analysis and detection capabilities
- v3.5.5 includes critical bug fixes and performance improvements
- Enhanced probe configurations improve service reliability and reduce false positive failures
- Structured metadata and volume enablement support …
> feat: enhance Loki with pattern ingester, TSDB schema upgrade, and v3.5.5 image
